### PR TITLE
Use double quotes in SQL alias member path

### LINKED ISSUE #912: Opening source from a filter with a lib name with a dot (e.g. LIB.MORE) produces *FILE not found (42704) error.
Opening source from a filter with a lib name with a dot (e.g. LIB.MORE) produces *FILE not found (42704) error in editor screen.  "Try Again" produces Window dialogue with the same error.  (I removed the errors under Errors section as they were unrelated and contained PI.
image
image
image

* QCCSID: 37
* Features:
   * git: true
   * grep: true
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[

]
```

### PR DESCRIPTION
**Pull request by worksofliam**
### Changes

Fix to alias path to use double quotes to allow for dots and other characters in the object names.

Was assisted by @forstie on this fix.

Fixes #912.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by worksofliam** [comment]
@chrjorgensen Any chance you can quickly give this a test? SQL and source member dates must be enabled.

**Comment by chrjorgensen** [comment]
@worksofliam Ah yes, dots in name will make the SQL for the ALIAS wrong, since a dot is used in SQL to separate schema, table etc.

I will test this tomorrow and give you feedback on this.

**Comment by forstie** [comment]
Good work!

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
@worksofliam The fix is not enough, I still get an error opening a member in TEST.DOT/QCLSRC:

```
/home/NCCJ/Develop/ServiceCommander-IBMi/: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
CREATE OR REPLACE ALIAS ILEDITOR.TEST.DOT_QCLSRC_MEMBER for "TEST.DOT"."QCLSRC"("MEMBER")
{
    "code": 4,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 42705\nNATIVE ERROR CODE: -950\nRelational database ILEDITOR not in relational database directory.",
    "stderr": ""
}
```

Your alias name should also have any dots replaced by underscore - maybe like this:

```javascript
const alias = `${lib}_${spf}_${mbr}`.replace(/\./g, `_`);
```

There is also a problem showing source line dates for the member from `TEST.DOT/QCLSRC`. I see that the sourcedates are indexed by the alias name, so there probably needs more changes in reading the dates - maybe a common alias name function?

**Comment by forstie** [comment]
The ideal solution will leverage QSYS2.DELIMIT_NAME().
I'll cover this in my Hidden Gems session in Denmark.

**Comment by worksofliam** [comment]
@chrjorgensen I did you suggestion and fixed all places where we generate an alias name.

Let me know what you think.. and another test when you have a minute.

**Review by chrjorgensen — APPROVED** [review]
@worksofliam It's looking good - and the source dates are working now. 👌

**Comment by worksofliam** [comment]
@chrjorgensen Neat!! Thank you friend

**Pull request merged**
