### PR TITLE
Converted CompileTools to TypeScript

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
Converted `CompileTools` to TypeScript

### Checklist
* [x] have tested my change
* [x] updated relevant documentation
* [x] eslint is not complaining

### CODE REVIEW

**Comment by worksofliam** [comment]
Code looks awesome. Needs further testing, which I can do tomorrow.

**Comment by sebjulliand** [comment]
> @sebjulliand I am going to wait for the md5 merge before I continue to review this. Might be worth bringing back changes from `master` after that merge too.

Agreed, I'll pull the updated master and resolve conflicts on the remaining PRs.

**Comment by worksofliam** [comment]
@sebjulliand Let me know when you've fixed the conflicts here and it will be my next task!

**Comment by sebjulliand** [comment]
> @sebjulliand Let me know when you've fixed the conflicts here and it will be my next task!

@worksofliam OK, you're good to go!

**Pull request merged**
