### PR TITLE
Do not prevent files listing if ls/stat has error(s)

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
Fixes issue https://github.com/halcyon-tech/vscode-ibmi/issues/1299
This PR lets the `getFileList` method parse `ls` or `stat` output even if the call return code is not 0. Error output is reported as error notifications (one per error).

### Checklist
* [x] have tested my change
* [x] eslint is not complaining
* [x] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
@sebjulliand It works almost as if I wrote it...! 🤣 

Very nice - just one minor thing: Can you make ignore the following error in `stat`:

billede

This appears when opening an empty directory. Maybe it could be filtered out of stderr?

Another minor issue, which may not be a new issue, is this error when opening a symlink to a directory using `ls`:

billede

billede

This is not a problem when using `stat`:

billede

**Comment by sebjulliand** [comment]
Thanks for the feedback @chrjorgensen, right on point as always 😊
The error when stat runs on an empty directory is gone again.

And I figured out that the error raised when opening a symlink to a directory using `ls` was occurring with `/usr/bin/ls` but not with `/QOpenSys/pkgs/bin/ls`. So I added `ls` to the connections' Remote Feature, looking in both locations in the event it's not found in `/QOpenSys/pkgs/bin`. I also reordered the locations in the Remote Feature so that `/QOpenSys/pkgs/bin` are used in priority over `/usr/bin`'s.

Everything should be fine now. Let me know how it goes 😉

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
@sebjulliand Perfect - code works as requested. I especially like your ordering of the remote features, so the OSS tools are preferred over the PASE tools! 🚀 

But why the commit https://github.com/halcyon-tech/vscode-ibmi/pull/1302/commits/e25aff277f8c3871364ce07b7b8ca468b8c278fa? It does not seem related to the ls/stat issue...?

**Comment by sebjulliand** [comment]
> @sebjulliand Perfect - code works as requested. I especially like your ordering of the remote features, so the OSS tools are preferred over the PASE tools! 🚀
> 
> But why the commit [e25aff2](https://github.com/halcyon-tech/vscode-ibmi/commit/e25aff277f8c3871364ce07b7b8ca468b8c278fa)? It does not seem related to the ls/stat issue...?

Ugh, I activated the `reorganize import on save` action and those two were reorganize...so I thought it wouldn't hurt to have them pushed as well 😅

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
@sebjulliand What happened to the commit https://github.com/halcyon-tech/vscode-ibmi/pull/1302/commits/ffc5b9240e66227fa02e8732e873b35c66122b54? Seems like it is not in the code anymore - did you do a merge/rebase on the master branch and forgot this?

**Comment by sebjulliand** [comment]
> @sebjulliand What happened to the commit [ffc5b92](https://github.com/halcyon-tech/vscode-ibmi/commit/ffc5b9240e66227fa02e8732e873b35c66122b54)? Seems like it is not in the code anymore - did you do a merge/rebase on the master branch and forgot this?

Gasp, you're right! I did a rebase that went wrong apparently and I didn't merge this part properly. I restored it, it should be fine now.

Thank you and your keen eyes @chrjorgensen !

**Review by chrjorgensen — APPROVED** [review]
Perfect! 🎉

**Pull request merged**
