### PR TITLE
Expose `Deployment` namespace in `CodeForIBMi` API

### PR DESCRIPTION
**Pull request by SanjulaGanepola**
### Changes

Instead of just exposing the `deploy` function in the `CodeForIBMi` API, this PR exposes the entire `Deployment` namespace to give access to the other functions. In this PR, I also exported the 4 functions to retrieve files based on the deployment method so they can be reused by other extensions.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Review by sebjulliand — CHANGES_REQUESTED** [review]
The change is good and works fine. I tested it from another extension and using the Deployment namespace works.
However, now the entire namespace gets exported, I'd move the `initialize` method out of it since it's not meant to be exported and called.

**Comment by SanjulaGanepola** [comment]
That is a good point. However how can we go about moving the `initialize` function out because it access other functions/variables within the namespace which are not exported.

**Comment by SanjulaGanepola** [comment]
Yeah that can work. Since the other functions are still related to Deployment, I think it would still be a good idea to have them in their own namespace. I think we keep the `Deployment` namespace to contain deployment related variables/helper functions and create a new namespace called `DeployTools` that will contain the functions we would like to have in the exported API.

@worksofliam @sebjulliand Any issues with this or can I go ahead and make this change?

**Comment by sebjulliand** [comment]
> Yeah that can work. Since the other functions are still related to Deployment, I think it would still be a good idea to have them in their own namespace. I think we keep the `Deployment` namespace to contain deployment related variables/helper functions and create a new namespace called `DeployTools` that will contain the functions we would like to have in the exported API.
> 
> @worksofliam @sebjulliand Any issues with this or can I go ahead and make this change?

Sounds good to me!

**Comment by SanjulaGanepola** [comment]
PR is ready for review.

**Changes:**
- `Deployment` namespace contains the deployment related variables/helper functions
- `DeployTools` namespace contains the APIs to be exposed for other extensions to use. I also included some more functions here compared to before as other extensions may want to use them
- Updated the `CodeForIBMi` to include `DeployTools`
- Renamed Deployment tests to Deploy Tools

**Review by sebjulliand — APPROVED** [review]
Perfect! Looks good to me and tests are still OK.

**Pull request merged**
