### PR TITLE
Control UI UX for running Actions

### PR DESCRIPTION
**Pull request by worksofliam**
## Changes

Adds a new connection setting so the user can control what UX they want when running an Action.

### How to test

1. Set to 'Show Action'
   * Expect only the task to show as the Action is started
2. Set to 'Show Problems'
   * Expect only the Problems view to show when the Action has been run
3. Set to 'None'
   * Expect no views to be shown

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by sebjulliand** [comment]
- Pushed `Open Output` commit
- Completed the description

**Review by sebjulliand — COMMENTED** [review]
It works as expected.
I'll leave it to you @worksofliam or @chrjorgensen to approve the `Open Output` change before merging.

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
@worksofliam Code is working as expected - I only have one question:

Shouldn't the configuration setting be a global one, working for all connections? This is a UI change and I would have thought it was a global setting... ❓

**Review by chrjorgensen — APPROVED** [review]
@worksofliam LGTM - approved! 😃 

Merge whenever you feel for it...

**Pull request merged**
