### PR TITLE
Converted Storage to TypeScript

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
* Converted Storage class source code to TypeScript
* Made get/set methods private
* Created explicit accessors for each stored object
* Created specific interface for paths content storage

### Checklist
* [x] have tested my change
* [x] updated relevant documentation
* [x] eslint is not complaining

### CODE REVIEW

**Comment by worksofliam** [comment]
@sebjulliand Any chance you can fix up those merge conflicts and then re-assign to me + request my review? Thanks!

**Comment by sebjulliand** [comment]
@worksofliam all done! I can't seem to reassign you though 🤔 (but I stupidly unassigned me)

**Comment by worksofliam** [comment]
@sebjulliand Sorry I didn't do this today. Some other things came up (939) and needed to get that done first. Will hopefully get this done tomorrow.

Thanks!

**Comment by sebjulliand** [comment]
No worries @worksofliam !

**Comment by worksofliam** [comment]
* [x] `getSourceList` and `setSourceList` working
* [x] `getLastProfile` and `setLastProfile` working
* [x] `getPreviousCurLibs` and `setPreviousCurLibs` working
* [x] `getDeployment` and `setDeployment` working

Thanks, @sebjulliand - this is a lovely cleanup.

**Pull request merged**
