### PR TITLE
Update webview-elements to 0.12.0

### LINKED ISSUE #1124: Update UI toolkit
We're way behind on our UI toolkit version. This isn't a problem for security, but we may be lacking in functionality due to how our current framework is changing.

In our deps:

```js
"@bendera/vscode-webview-elements": "^0.6.3",
```

But I see that this framework [just released 0.10.1](https://github.com/bendera/vscode-webview-elements/releases), and 0.8.0 was a huge, possibly breaking change.

Now that our `CustomUI` code is really cleaned up, I wonder if it's time to start making some changes:

1. Update our version of `@bendera/vscode-webview-elements`
2. Switch to Microsoft's [vscode-webview-ui-toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit)

Both might have a large impact, but if we select number 2, this is what I know:

* file selects are not fully supported
* I think we should replace our `tree` field with something else, or fully remove it. It is only used in the Actions webview.

### PR DESCRIPTION
**Pull request by worksofliam**
### Changes

Updatse webview-elements to 0.12.0 and closes #1124.

It mostly works the same. ~though the spacing isn't the same~.

~Also see this issue regarding `file` CustomUI type: https://github.com/bendera/vscode-webview-elements/issues/47~

Would like these merged before this can be merged:

* #1130 
* #1120

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by bendera** [comment]
Hi,

I found a CSS margin issue in the settings-form variation of FormGroup and this affects your extension. I've fixed it in the 0.10.3

**Comment by chrjorgensen** [comment]
@worksofliam Maybe we should go to the newest [release 0.11.0](https://github.com/bendera/vscode-webview-elements/releases/tag/v0.11.0) of the toolkit? Doesn't seem to contain any changes with consequences for us - and with the can open... 😉

**Comment by bendera** [comment]
If you could wait a few more days I would add some improvements.

- Until now the Textarea component had a fixed default width but if the cols attribute is set, the inner textarea element always will be wider or narrower than the component itself. I've already fixed this but I haven't published it yet.
- I will customize the native, ugly, and gray browser button in the file input.

**Comment by bendera** [comment]
Done.
https://bendera.github.io/vscode-webview-elements/components/vscode-textfield/#file-input
https://bendera.github.io/vscode-webview-elements/components/vscode-textarea/#rows-and-cols-attributes

**Comment by worksofliam** [comment]
@bendera Thank you for the CSS fixes and the likes!

@chrjorgensen I've cleaned up the code further and bumped webview-elements to 0.12.0.

Are you able to give it another run through for me whenever you have a moment? Thanks!

**Review by chrjorgensen — DISMISSED** [review]
@worksofliam LGTM - I gave it a spin and went through the following, where there is UI:

- connection settings
- login settings
- actions
- custom variables

All looked good and I found no errors.

**Comment by worksofliam** [comment]
Fixed and tested again myself to be sure and it's all looking good. I am going to merge.

Thank you @chrjorgensen for your review! And thank you @bendera for supporting us with your fast releases :)

**Pull request merged**
