### PR TITLE
Converted Actions Maintenance editor to TypeScript + added translations

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
- Converted the Actions Maintenance editor to TypeScript.
- Extracted Locale constants and added FR translations.

@chrjorgensen , feel free to add a commit to provide the following Danish translations (big thanks in advance):
```
'duplicate':'Duplicate',
'save':'Save',
'delete':'Delete',
'cancel':'Cancel',
...
//Actions
'actions.CURLIB': 'Current library, changeable in Library List',
'actions.USERNAME': `Username for connection`,
'actions.HOME': `Current home/working directory, changable in IFS Browser`,
'actions.BUILDIB': `The same as <code>&amp;CURLIB</code>`,
'actions.LIBLC': `Library list delimited by comma`,
'actions.LIBLS': `Library list delimited by space`,
'actions.OPENLIB': `Library name where the source member lives (<code>&amp;OPENLIBL</code> for lowercase)`,
'actions.OPENSPF': `Source file name where the source member lives (<code>&amp;OPENSPFL</code> for lowercase)`,
'actions.OPENMBR': `Name of the source member (<code>&amp;OPENMBRL</code> for lowercase)`,
'actions.member.EXT': `Extension of the source member (<code>&amp;EXTL</code> for lowercase)`,
'actions.FULLPATH': `Full path of the file on the remote system`,
'actions.RELATIVEPATH': `Relative path of the streamfile from the home directory or workspace`,
'actions.PARENT': `Name of the parent directory or source file`,
'actions.BASENAME': `Name of the file, including the extension`,
'actions.streamfile.NAME': `Name of the file (<code>&amp;NAMEL</code> for lowercase)`,
'actions.streamfile.EXT': `Extension of the file (<code>&amp;EXTL</code> for lowercase)`,
'actions.LIBRARY': `Library name where the object lives (<code>&amp;LIBRARYL</code> for lowercase)`,
'actions.NAME': `Name of the object (<code>&amp;NAMEL</code> for lowercase)`,
'actions.object.TYPE': `Type of the object (<code>&amp;TYPEL</code> for lowercase)`,
'actions.object.EXT': `Extension/attribute of the object (<code>&amp;EXTL</code> for lowercase)`,
'actions.mainMenu.workWithActions': `Work with Actions`,
'actions.mainMenu.createOrMaintain': `Create or maintain Actions. Actions are grouped by the type of file/object they target.`,
'actions.mainMenu.newAction': `New Action`,
'actions.duplicate.select': `Select an action to duplicate`,
'actions.workAction.create.title': `Create action`,
'actions.workAction.edit.title': `Edit action "{0}"`,
'actions.workAction.duplicate.title': `Duplicate action "{0}"`,
'actions.workAction.name': `Action name`,
'actions.workAction.command': `Command(s) to run`,
'actions.workAction.command.description': `Below are available variables based on the Type you have select below. You can specify different commands on each line. Each command run is stateless and run in their own job.`,
'actions.workAction.extensions': `Extensions`,
'actions.workAction.extensions.description': `A comma delimited list of extensions for this action. This can be a member extension, a streamfile extension, an object type or an object attribute`,
'actions.workAction.types': `Type`,
'actions.workAction.types.description': `The types of files this action can support.`,
'actions.workAction.types.member': `Member`,
'actions.workAction.types.member.description': `Source members in the QSYS file system`,
'actions.workAction.types.streamfile': `Streamfile`,
'actions.workAction.types.streamfile.description': `Streamfiles in the IFS`,
'actions.workAction.types.object': `Object`,
'actions.workAction.types.object.description': `Objects in the QSYS file system`,
'actions.workAction.types.file': `Local File (Workspace)`,
'actions.workAction.types.file.description': `Actions for local files in the VS Code Workspace.`,
'actions.workAction.environment': `Environment`,
'actions.workAction.environment.description': `Environment for command to be executed in.`,
'actions.workAction.environment.ile': `ILE`,
'actions.workAction.environment.ile.description': `Runs as an ILE command`,
'actions.workAction.environment.qsh': `QShell`,
'actions.workAction.environment.qsh.description': `Runs the command through QShell`,
'actions.workAction.environment.pase': `PASE`,
'actions.workAction.environment.pase.description': `Runs the command in the PASE environment`,
'actions.workAction.delete.confirm': `Are you sure you want to delete the action "{0}"?`
```

### Checklist
* [x] have tested my change
* [x] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Review by chrjorgensen — DISMISSED** [review]
@sebjulliand Texts has now been translated into Danish - with some minor fixes as well.
I also did some functional testing of the new Action Maintenance editor, and all is looking good! 😍 

Feel free to merge when you like. 👍

**Comment by sebjulliand** [comment]
Thanks for te fixes and the review @chrjorgensen; much appreciated!

**Comment by sebjulliand** [comment]
@chrjorgensen woops, looks like I made a mess while rebasing...could you approve again? Thanks!

**Comment by chrjorgensen** [comment]
@sebjulliand All good - I have made some minor changes and added `&HOST` to the Action Maintenance view.

Will you translate

```
'actions.HOST': `Hostname or IP address from the current connection`,
```

into French? When done, I will approve and merge.

**Review by chrjorgensen — APPROVED** [review]
@sebjulliand Well done, Mr. TypeScript! 😄

**Pull request merged**
