### PR TITLE
Support local `.evfevent` folder

### PR DESCRIPTION
**Pull request by worksofliam**
### Changes

To improve local development, this PR enables both loading compile errors from the server (when working in members or streamfiles), but also allows for loading errors from a local `.evfevent` file, which is a directory build tools are using (ibmi-bob and custom make rules) to store compile errors. **There is no impact to user experience here for those working with source members or streamfiles.**

It will only load from the local `.evfevent` folder when `.evfevent` is specified in the `postDownload` property in `actions.json`.

A number of other small, but important changes

* `tryNewErrorParser` is now `true` by default. It's needed, other SQL errors don't render.
* Removed message that shows the users current library when connecting to a system. This error message was often wrong because my builds tools override the current library outside of the Code for IBM i config.
* Removed question asking if newly created libraries should be added to the user library list.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Review by Wright4i — APPROVED** [review]
@chrjorgensen approved. Code looks good. Tested and everything worked as expected, minor issue I tried `postDownloads` but it's `postDownload` no s. 

Builds worked with source members and streamfiles. I tried without this change, with the changes with and without postDownload set to `.evfevent` using Bob.

My only ask would be for after this is merged and we have the big **2.1.0** 🥳 
release it'd be nice to see the relevant docs updated for others coming over and trying to use Bob. Links below.

1. [Workspace Actions in halcyon-tech/docs](https://github.com/halcyon-tech/docs/blob/main/docs/pages/developing/local/getting-started.md#4-workspace-actions-deploy--build)
2. [Code for IBM i docs in IBM/ibmi-bob](https://github.com/IBM/ibmi-bob/blob/master/docs/integration/code-for-ibm-i.md#developing-on-the-local-machine-with-ibmi-bob)

**Comment by Wright4i** [comment]
@worksofliam was just a stumbling point so I wanted to call out. You had it spelled plural in your changes, but it's coded singular. It's fine without the `s` so long as it's documented without the `s`.

**Comment by worksofliam** [comment]
@Wright4i Sorry to be a real PITA. If you get another chance, can you have another go over of this? The merge commit was huge and I'd like more eyes than just me on it.

**Comment by worksofliam** [comment]
Made further changes to improve error messages for ILE compiles vs pase command execution. I just tested some ILE compiles and there is no impact as expected.

**Comment by SanjulaGanepola** [comment]
@worksofliam Changes look good. Thanks!

**Comment by Wright4i** [comment]
@worksofliam LGTM!

**Pull request merged**
