### PR TITLE
Typescript/languageactions

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
* Converted `LocalLanguageActions` to TypeScript
* `type` in `Action` is now optional (or `type` would have to be defined on every predefined action)

### Checklist
* [x] have tested my change
* [x] updated relevant documentation
* [x] eslint is not complaining

### CODE REVIEW

**Comment by worksofliam** [comment]
@sebjulliand There may be a conflict here as I need to put a fix in for the deployment stuff.

**Comment by sebjulliand** [comment]
No worries, just push your fix and I'll update the PR afterwards.

**Comment by worksofliam** [comment]
@sebjulliand Looks like no conflicts after all! I will assign this to me.

**Comment by worksofliam** [comment]
@sebjulliand Any chance you can fix up those merge conflicts and then re-assign to me + request my review? Thanks!

**Comment by sebjulliand** [comment]
Here you go @worksofliam!

**Comment by worksofliam** [comment]
@sebjulliand Looks like this had the config PR globed on top of this PR. Not a problem, just GitHub being a pain.

This one will require a bit more time since of all the different places Actions can be called from. I will do that today and hopefully get this in today as well.

**Comment by worksofliam** [comment]
@sebjulliand Sorry - think this conflict was me! Any chance you can fix this before I review?

**Comment by sebjulliand** [comment]
@worksofliam Sure thing!

**Comment by worksofliam** [comment]
@sebjulliand Maybe this is going to sound like a PITA.. is there any chance this PR can be re-opened? It's pretty difficult doing this code review due to the fact that all the other PRs are appearing in the changed code. What do you think?

**Comment by sebjulliand** [comment]
I completely agree, not a problem at all. I'll clean my mess!

**Pull request closed without merging**
