### PR TITLE
Converted Tools to TypeScript

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
* Converted code to TypeScript
* Introduced `Tools` namespace
* Introduced `DB2Row` interface
* Moved optional parameters to end of methods signature where relevant

### Checklist
* [x] have tested my change
* [x] updated relevant documentation
* [x] eslint is not complaining

### CODE REVIEW

**Comment by worksofliam** [comment]
@sebjulliand I think your other PR merge has created a minor conflict here. I am going to fix it myself.

**Review by worksofliam — CHANGES_REQUESTED** [review]
@sebjulliand looks good to me! Another very nice change - thanks.

Last thing I need you to do before I can merge this is bring the changes in from `master` so I can do some testing with your merged PR.

Thanks!

**Comment by sebjulliand** [comment]
And done!
Thanks for the kinds words @worksofliam.

**Comment by worksofliam** [comment]
Thanks @sebjulliand! You're doing such an awesome job.

**Pull request merged**
