### PR TITLE
Fixed dropped connection handling + allow force disconnection

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
- Fixed disconnection failing when connection was dropped unexpectedly
- Allow to try reconnecting at will; if re-connecting fails, the following modal dialog will show up:
image
- Allow to force disconnection when dirty editors are still opened
image
- Keep dirty editors opened when disconnecting forcefully

### Checklist
* [x] have tested my change

### CODE REVIEW

**Comment by worksofliam** [comment]
@sebjulliand Additional commit made to only close members, streamfiles and objects.

**Comment by worksofliam** [comment]
@sebjulliand Code looks ok to me and tested the disconnect handler by turning off the VPN! Please give my change a quick review and we should be ok to merge this.

**Review by sebjulliand — COMMENTED** [review]
👍🏻

**Review by sebjulliand — COMMENTED** [review]
OK

**Review by worksofliam — APPROVED** [review]
Looks good and tests good to me. Thanks!

@sebjulliand merge whenever you're ready.

**Pull request merged**
