### PR TITLE
Proposal: API tests

### PR DESCRIPTION
**Pull request by worksofliam**
### Changes

Our API is getting large.

I am proposing a testing suite that will allow us to test:

* Our export API
* Commands that we register

I am not using jest, mocha or vitest here so we can simply integrate easily into how we do development. The reason I am not using the testing suite that comes with VS Code (`vscode-test` package) is because of our dependency on the connection. I've built this so the tests can be triggered when we make a connection (plus we could even automate the connection with our `connectDirect` API)

Something that needs to be figured out:

* Not shipping our test code in production builds
* This can be done in our webpack config I bet

### CODE REVIEW

**Comment by worksofliam** [comment]
https://stackoverflow.com/questions/52059366/how-to-exclude-directory-from-getting-bundled-by-webpack

**Comment by worksofliam** [comment]
@chrjorgensen @sebjulliand This PR is now ready to review. I've now got it building our production `.vsix` without the tests.

**Webpack development built**

```
barrymac:vscode-ibmi barry$ npm run webpack

> code-for-ibmi@1.7.12 webpack
> webpack --mode development

Is production build: false
asset extension.js 1.53 MiB [emitted] (name: main) 1 related asset
runtime modules 937 bytes 4 modules
cacheable modules 1.42 MiB
  modules by path ./node_modules/ 1.03 MiB
    javascript modules 911 KiB 68 modules
    ./node_modules/@bendera/vscode-webview-elements/dist/bundled.js 141 KiB [built] [code generated]
    ./node_modules/ssh2-streams/package.json 590 bytes [built] [code generated]
  modules by path ./src/ 397 KiB 48 modules
+ 18 modules
webpack 5.76.0 compiled successfully in 1060 ms
```

**Webpack production build**

```
barrymac:vscode-ibmi barry$ npm run package

> code-for-ibmi@1.7.12 package
> vsce package

Executing prepublish script 'npm run vscode:prepublish'...

> code-for-ibmi@1.7.12 vscode:prepublish
> webpack --mode production

Is production build: true
asset extension.js 727 KiB [emitted] [minimized] (name: main) 2 related assets
orphan modules 244 KiB [orphan] 40 modules
runtime modules 937 bytes 4 modules
modules by path ./ 1.42 MiB
  modules by path ./node_modules/ 971 KiB
    javascript modules 830 KiB 56 modules
    ./node_modules/@bendera/vscode-webview-elements/dist/bundled.js 141 KiB [built] [code generated]
    ./node_modules/ssh2-streams/package.json 590 bytes [built] [code generated]
  modules by path ./src/ 478 KiB 21 modules
+ 17 modules
webpack 5.76.0 compiled successfully in 6110 ms
 DONE  Packaged: /Users/barry/Repos/vscode-ibmi/code-for-ibmi-1.7.12.vsix (90 files, 367.45KB)
 INFO  
```

**To run the tests**, start debugging the `Extension Tests` configuration and connect to a system for the tests to run.

image

image

**Review by chrjorgensen — COMMENTED** [review]
@worksofliam Code looks good to me and it works as described.

@sebjulliand I will leave it up to you to review, test, approve and merge...

**Comment by sebjulliand** [comment]
@worksofliam I was thinking about committing a simple UI to display the tests and their results. What do you think?

**Comment by worksofliam** [comment]
@sebjulliand it's a good idea. Ideally we should stick it in another PR.

**Review by sebjulliand — APPROVED** [review]
We're off to a good start in the testing department!

**Pull request merged**
