### PR TITLE
Fix display of empty and non-existing directories

### PR DESCRIPTION
**Pull request by chrjorgensen**
### Changes

This PR will fix the display of non-existing and empty directories in the IFS browser. Now errors will be caught for `stat` output:

billede

And the list of files will only be generated when the directory has content (`stdout` is not blank).

billede

The PR was created to fix issue #1325.

Additional tests and fixes:
- Test for getting non-existing IFS file
- Fix test getFileList for QSYS.LIB (path was not valid, owner was added)
- Fix test of runCommand API
- Allow lowercase member and extension in getMemberList (previously only library and sourcefile were uppercased)
- Fix test of getMemberList (SQL, no filter) (number of members in QSYSINC/MIH varied across releases)
- Pad member dates and times with zeros (non-SQL) (made timestamp creation fail)
- Test for valid directory when creating IFS shortcut (as suggested by @sebjulliand)

### Checklist

* [x] have tested my change
* [x] eslint is not complaining

### CODE REVIEW

**Comment by worksofliam** [comment]
@chrjorgensen What are the chances for adding a test to ensure the API fails when passed an invalid directory?

**Review by sebjulliand — APPROVED** [review]
Code looks good and works as expected. Good one!

I'd have one suggestion though: how about adding a test in the `code-for-ibmi.addIFSShortcut` command, to check if the path exist and is an actual directory (by calling `IBMiContent.isDirectrory` method)?

**Comment by chrjorgensen** [comment]
@worksofliam @sebjulliand Adding test for non-existing IFS streamfile/directory revealed several issues and errors, which has now been fixed. Please review... :eyes:

**Comment by worksofliam** [comment]
@chrjorgensen The tests are working great!

I hate to be such a burden, but I noticed one of our internal APIs is using `showErrorMessage`, which I don't believe is something our internal API should be doing and should be handled by the views calling the APIs instead:

https://github.com/chrjorgensen/code-for-ibmi/blob/fix/non-existing-dir-in-IFS-browser/src/api/IBMiContent.ts#L636

Is there any chance this PR could clean it up and throw an error instead of logging them to the user like this?

**Comment by chrjorgensen** [comment]
@worksofliam
I agree that an internal API should not write to the UI - but I'm not sure how to fix this: There could be many errors (non-existing symlinks, authorities etc) and the only this could be passed back to the caller is to change the return structure (e.g. combine array IFSFile and the error information in a new structure). This could be a breaking change and should probably wait for version 2.0.0, right?

@sebjulliand
This is beyond (above?) my TypeScript knowledge, I think. You're our TypeScript guru... 😉  ...what do you think - any ideas?

**Review by worksofliam — APPROVED** [review]
I am happy with the test coverage (and fixes, thank you!!) and the fix you have made for the bug.

**Comment by sebjulliand** [comment]
> @sebjulliand This is beyond (above?) my TypeScript knowledge, I think. You're our TypeScript guru... 😉 ...what do you think - any ideas?

Oh you...don't say it too much or I'll start to believe it 😁
It's actually simple: the is a `isDirectory()` method to test if a path is a directory. I was thinking we could call it when adding a shortcut to check if the shortcut points to a directory in the first place. But I can make a PR for that if you wish, once this one gets merged.

**Comment by worksofliam** [comment]
@sebjulliand 

> But I can make a PR for that if you wish, once this one gets merged.

Let's do that! I'd appreciate it. 

I am going to merge this and get a new fix release out.

**Pull request merged**
