### PR TITLE
Add support for ${userHome} and ${pathSeparator} in Connections settings.

### PR DESCRIPTION
**Pull request by ScottKlement**
### Changes

Description of change here.

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by ThePrez** [comment]
Gneiss!

**Comment by worksofliam** [comment]
Thanks for your PR, @ScottKlement! I am just recovering from being a little ill so I will get around to this ASAP.

**Comment by worksofliam** [comment]
@ScottKlement An excellent PR. Thank you!

I must request that `configVars.js` be converted to TypeScript. As of about 5 months ago, any new code must be in TypeScript.

**Comment by ScottKlement** [comment]
I've made an attempt at rewriting it in TypeScript -- this is the first time I've used TypeScript, so please look it over.

**Comment by worksofliam** [comment]
@ScottKlement looks ok to me! I'll get a formal review in tomorrow. Cheers

**Comment by worksofliam** [comment]
@ScottKlement Looks great! Thanks for your first PR 🎉

**Pull request merged**
