### PR TITLE
Add a disconnect button to status bar

### PR DESCRIPTION
**Pull request by sebCIL**
### Changes

Add a disconnect button to status bar.
2022-08-24_12h13_05

### Checklist

* [X] have tested my change
* [ ] updated relevant documentation
* [X] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Review by worksofliam — CHANGES_REQUESTED** [review]
A very good change, but I don't want this button shown by default. In this same file we also add the reconnect button, but it hidden by default. Here's what I think we should:

* Rename config `showReconnectButton` to `showConnectionButtons`
* Like the reconnect button, only show the disconnect button when `showConnectionButtons` is enabled

**Comment by sebCIL** [comment]
Ok, it only show the disconnect button when `showConnectionButtons` is enabled.
I have made the modification in `package.json` too but how to convert `showReconnectButton` to `showConnectionButtons` in the configuration file?

**Comment by worksofliam** [comment]
@sebCIL Awesome!

> I have made the modification in package.json too but how to convert showReconnectButton to showConnectionButtons in the configuration file?

There is no way to convert. `showConnectionButtons` will be treated as a new property and the old one will be ignored in the future.

I will review today!

**Review by worksofliam — APPROVED** [review]
Testing both enabled and disabled. Looks great! Thank you!

**Pull request merged**
