### PR TITLE
Multi language support Documentation site (docsify)

### PR DESCRIPTION
**Pull request by novy400**
### Changes

- Add a french translation (not finished at once) to the Code For IBM i documentation (Docsify).
- Propose a process to add new translations to this site (translating.md).
👁‍🗨 https://novy400.github.io/vscode-ibmi/#/
### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by worksofliam** [comment]
This is SO awesome @novy400!! I have to spend some time to go over the content but it's looking good so far.

I think a goal after this has been merged is to move the docs into a separate repository, because I think it's going to continue to grow.

**Comment by novy400** [comment]
Cool Thanks @worksofliam ! Yes I'm agree with you. it's better to have an separate repository for the documentation site. But I don't know if it's possible to keep the url halcyon-tech.github.io/vscode-ibmi/#/ I hope so !

**Comment by worksofliam** [comment]
> But I don't know if it's possible to keep the url halcyon-tech.github.io/vscode-ibmi/#/ I hope so !

I think I will be able to setup a redirect!

If I make a new repo, would you be able to make the PR again over there? I will do it later today.

**Comment by worksofliam** [comment]
@novy400 Please apply a new PR to the new docs repo here!

https://github.com/halcyon-tech/docs

**Comment by novy400** [comment]
Hi Liam Yes I'm going to apply a new PR on the new repo .

**Pull request closed without merging**
