### PR TITLE
Always show Terminal and Debugger tabs in settings

### PR DESCRIPTION
**Pull request by shamby87**
### Changes

Always show Terminals and Debugger tabs in connection settings, warning the user if they need to connect or enable a service to change the settings.

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by shamby87** [comment]
resolves #1314 

May want to reword the warning messages, wasn't exactly sure what we should tell the user in the case where the tab can't yet be used.

**Review by worksofliam — CHANGES_REQUESTED** [review]
@shamby87 Change is great, but I don't think a heading is very suited.

image

Can we use a paragraph instead?

**Review by shamby87 — COMMENTED** [review]
Changed to paragraph

**Comment by worksofliam** [comment]
@shamby87 Perfect - thanks!

**Pull request merged**
