### PR TITLE
Upgrade node-ssh to 13.1

### PR DESCRIPTION
**Pull request by worksofliam**
### Changes

Finally upgraded node-ssh to 13.1. We failed to do it in the past because ssh2 (a sub dep) now builds binaries for the package, **but they are optional**. I have updated our webpack configuration to ignore the errors for those binary files.

See this issue for how someone else fixed it: https://github.com/mscdex/ssh2/issues/1213

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by worksofliam** [comment]
Tests are passing as expected under this branch: 

image

**Review by sebjulliand — DISMISSED** [review]
Everything seems to work fine on my end.
I tried a little bit of everything and didn't notice any issue.
I also packaged the extension and installed it. Didn't have any issue. Good one!

**Review by chrjorgensen — DISMISSED** [review]
I checked out this PR and did some regular development on our IBM i - and found no issues.

**Comment by worksofliam** [comment]
Ok, I think we've deemed this mergeable. I will do this today after resolving the conflict.

**Pull request merged**
