### PR TITLE
Added "protected" option to filters

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
Added a `protected` setting to Object filters, as a possible answer to issue https://github.com/orgs/halcyon-tech/discussions/1048.

When a filter is protected:
- a lock icon is shown next to its name
- no modifying action can be taken on any of its children
- members can be opened but cannot be saved
- members listed from a `protected` filter search cannot be saved

The `ctrl+alt+o` shortcut is now `Go to file (read only)` and allows to open members in protected mode (i.e. save is disabled).

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] eslint is not complaining
* [x] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by chrjorgensen** [comment]
@sebjulliand You rock! Can't wait to test this new function...!! 🚀 
But @worksofliam has been busy this Sunday, and I think you'll have to merge the master branch in once more - GitHub reports conflicts... 😉

**Comment by worksofliam** [comment]
@chrjorgensen is right!

Also, not sure what happened, but it seems the 'Files changed' is kind of messed up for this PR?!

**Comment by sebjulliand** [comment]
Right, it's merged...it's odd though, Git always struggle to merge some changes sometimes (or as Liam said it's because I still have too many branches open).
Anyway, it should be ok now.

**Comment by worksofliam** [comment]
@sebjulliand I don't know if I'm going to be able to review this PR. The commit history is so ruined.

I think the best option is actually to bisect your original commit onto a new branch and create another PR. What do you think?

**Comment by sebjulliand** [comment]
> @sebjulliand I don't know if I'm going to be able to review this PR. The commit history is so ruined.
> 
> I think the best option is actually to bisect your original commit onto a new branch and create another PR. What do you think?

You're right @worksofliam ; I'll do that.
I think I'll do the same for this one https://github.com/halcyon-tech/vscode-ibmi/pull/1003 ; it's been stalling for quite a while now and merging will make a mess. I'll recreate both this week-end.

**Pull request closed without merging**
