### PR TITLE
Collapse all on IFS Browser and Object Browser #876

### PR DESCRIPTION
**Pull request by novy400**
### Changes

Description of change here.
add buttons to collapse the file in object Brower and ifs browser view.
image
About  updated relevant documentation I Have'nt seen usefull modification to do...

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by chrjorgensen** [comment]
Thanks, @novy400 , I will give it a spin tomorrow Sunday and get back to you.

**Review by chrjorgensen — APPROVED** [review]
@novy400 Excellent, your change works perfectly. Thanks for contributing! 😍

**Review by chrjorgensen — APPROVED** [review]

**Comment by sebjulliand** [comment]
A little suggestion/improvement, since vscode's collapse command takes the view id in its name: it may be nice to have a global `collapse` function, that would take a view in parameter and perform the command execution:
```typescript
export function collapse(viewId:string) {
    vscode.commands.executeCommand(`workbench.actions.treeView.${viewId}.collapseAll`);
}
```

Then, just registering each specific collapse commands like this would be enough:
```typescript
vscode.commands.registerCommand(`code-for-ibmi.collapseIFSBrowser`, () => collapse("ifsBrowser");
```

That would reduce code duplication and ease future view's collapse implementation 😉

**Comment by chrjorgensen** [comment]
@sebjulliand I think this is a great idea - but maybe it should be in a separate PR, combining all the collapseAll functions. It requires some JavaScript / Typescript knowledge, which we can't expect @novy400 to possess. 

@novy400 One small change - could you make the commit comment more descriptive, like `Add collapseAll button to Object Browser and IFS Browser`?

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
Please change commit message to be more descriptive...

**Comment by novy400** [comment]
@sebjulliand and @chrjorgensen perhaps I can change to use Collapse as a global function , but Yes I think it's better to do it in next PR. I'm going on vacation in a few days. but I'm going back next monday and I can try do it  then....

**Review by chrjorgensen — APPROVED** [review]
Much better... 👍

**Pull request merged**
