### PR TITLE
Converted to TypeScript and enhanced CustomUI 

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
* Converted `CustomUI` to TypeScript
* Added `addXXX` methods, where `XXX` is one of the supported `Field`'s type. These methods can be chained to easily create a form.
```ts
const formPage = await new CustomUI()
  .addInput('name', 'Name')
  .addInput('address', 'Address')
  .addCheckbox('trust','Trust')
  .addHorizontalRule()
  .addButtons({id: "ok", label:"Ok"}, {id: "cancel", label:"Cancel"})
  .loadPage('My form');

if(formPage){
  formPage.panel.dispose();
  if(formPage.data){
    //Do something with data
  }
}  
```
* Updated views to use new `CustomUI` methods

### Checklist
* [x] have tested my change
* [x] updated relevant documentation
* [x] eslint is not complaining

### CODE REVIEW

**Comment by worksofliam** [comment]
A very daring change, might I save, but a bloody might good improvement. This is a huge PR. A large portion of our user experience relies on this UI.

@sebjulliand Before I go ahead and review anything, would you be interested in meeting me so we can test together a little bit? I imagine there's some edge cases :)

**Comment by sebjulliand** [comment]
> A very daring change, might I save, but a bloody might good improvement. This is a huge PR. A large portion of our user experience relies on this UI.
> 
> @sebjulliand Before I go ahead and review anything, would you be interested in meeting me so we can test together a little bit? I imagine there's some edge cases :)

Sure thing, let me know when you want to meet!

**Comment by sebjulliand** [comment]
> > A very daring change, might I save, but a bloody might good improvement. This is a huge PR. A large portion of our user experience relies on this UI.
> > @sebjulliand Before I go ahead and review anything, would you be interested in meeting me so we can test together a little bit? I imagine there's some edge cases :)
> 
> Sure thing, let me know when you want to meet!

@worksofliam we should talk about it sooner than later, I had to merge over 100+ commits to fix the conflicts since the branch exists 😅

**Comment by sebjulliand** [comment]
Closed because messy.
Clean PR here: https://github.com/halcyon-tech/vscode-ibmi/pull/1076

**Pull request closed without merging**
