### PR TITLE
Fix/variant chars part two

### PR DESCRIPTION
**Pull request by chrjorgensen**
### Changes

This PR will change the member list SQL to ignore the CCSID on member data columns (by casting to FOR BIT DATA), which will return the data in the user CCSID. This will also make many conversions irrelevant and they have been removed.

It is a fix for issue #746 

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by chrjorgensen** [comment]
@worksofliam Sorry for the many commits - this branch was created on the branch for my previous PR. Are the commits in this PR also because they are not yet merged into master brancch?

The only commit added is [031663c](https://github.com/halcyon-tech/vscode-ibmi/pull/770/commits/031663cf1d68bf1e4014f6a924e3935da549d39b)

I have tested this on my system with many different CCSID's - and it looks okay to me. It even made the code simpler since I could remove some calls to the `sysNameInLocal` conversion routine.

**Comment by worksofliam** [comment]
@chrjorgensen No problem about the extra commits. For future reference, whenever I am working on two PRs I always branch off of master again because of this reason. I can see here this PR is really only one commit. 

I am going to review this now, but this is a very nifty change. I have learned something today.

**Comment by worksofliam** [comment]
@chrjorgensen This is a very cool change! I have tested and think it's awesome how this works now.

I am going to merge it today and likely get a release out in the next few days.

Separate question for you though: does this work down on 7.2 at all? In theory we support 7.2 and above.

**Comment by chrjorgensen** [comment]
@worksofliam

> Separate question for you though: does this work down on 7.2 at all? In theory we support 7.2 and above.

I don't have access to a system running 7.2, so I'm not able to test it on this release. Do you know any in your network having a server with 7.2?
Having said that, I see no reason why it shouldn't work on 7.2 - the SQL CAST to binary has been there for years and is available in [7.1](https://www.ibm.com/docs/en/i/7.1?topic=expressions-cast-specification) and probably even releases before that.

Do you think the creator of issue #746 should test the changes in a temporary release - before sending it out to the world?

**Comment by worksofliam** [comment]
@chrjorgensen i actually do have a 7.2 box, let me check this tonight. I will post back here with my results.

Though I do believe you are right. I think it will work fine on 7.2.

Thanks again!

**Pull request merged**
