### PR TITLE
Add check for additional user content in shell output

### PR DESCRIPTION
**Pull request by chrjorgensen**
### Changes

This PR will add a check for additional user content in the output from shell commands during connection, thus eliminating issues like #1255 and others with similar root cause.

If the user has a shell start script with `echo` or any other command, that sends output to stdout, then Code will not be able to interpret the output correctly, and the user will see some mysterious errors - see #1255. This new check will ensure no such additional user content is present, else an error will be issued and the connection attempt aborted.

billede

billede

billede

### Checklist

* [x] have tested my change
* [x] eslint is not complaining
* [x] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by chrjorgensen** [comment]
When this PR is merged into master, the check will be included in Quick Connect in an upcoming PR `Quick Connect part II`... 😉

**Comment by worksofliam** [comment]
@chrjorgensen I like it a lot! How can I test this? Is it as simple as writing an `echo` in my `.profile`?

**Comment by chrjorgensen** [comment]
@worksofliam I inserted an echo as the first line in my .bashrc file...

**Comment by worksofliam** [comment]
@chrjorgensen Awesome. This catches that great! We've had many issues, and you yourself just helped someone solve this recently.

My only thought is that I don't know if I want it to disconnect the user. Even if this error occurs, we can still open streamfiles in the IFS to fix the issue.

Perhaps instead of disconnecting them, we can warn the user that until the issue is fixed, Code for IBM i may not function correctly. We do this when a home directory isn't setup correctly.

**Comment by chrjorgensen** [comment]
@worksofliam 

> My only thought is that I don't know if I want it to disconnect the user. Even if this error occurs, we can still open streamfiles in the IFS to fix the issue.

I understand, but I was not sure IFS files could be opened with this configuration and wanted to avoid any mysterious errors in Code. But I will change it to just issue a warning "that everything may break"... 😆

**Review by sebjulliand — APPROVED** [review]
Change is good and works as expected, I'll approve it.
That's a clever check @chrjorgensen , it will probably help avoiding a lot of common issues 😅

**Comment by chrjorgensen** [comment]
> @worksofliam
> 
> > My only thought is that I don't know if I want it to disconnect the user. Even if this error occurs, we can still open streamfiles in the IFS to fix the issue.
> 
> I understand, but I was not sure IFS files could be opened with this configuration and wanted to avoid any mysterious errors in Code. But I will change it to just issue a warning "that everything may break"... 😆

@worksofliam I just did some testing, having Code continue with configuration error - and it is not possible to edit the IFS streamfile(s) with this config! The IFS browser shows "Error loading objects" and sends this error:

billede

And Ctrl-Alt-P returns this:

billede

So I think that a disconnect is the only sensible option...

**If you agree, will you merge this PR?**

**Comment by worksofliam** [comment]
I also tested this yesterday and forgot to reply here. You are completely right! Let's merge.

**Pull request merged**
