### PR TITLE
Converted Object Browser and Filter Editor to TypeScript

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
This PR converts the Object Browser view and Filter editor to TypeScript and brings a few enhancements as well:
- Commands that should not be called from the palette are now hidden from it
- Object Browser's TreeItem model types are now exported
- Added missing translations
- Commands try to refresh only the relevant part of the browser when possible
- Added a function to centralize configuration listeners

Some refactoring was in order, hopefully for the best. Any feedback is welcome.
I tested it as much as I could and ran every browser's command, but more user testing is required since it's a big change.

I'll update the extension's API documentation with the relevant information (commands, model, etc) once this is approved.

@chrjorgensen , can you provide the Danish translations for those items please? 😄 
```
'not.connected':'Not connected to an IBM i',
'text':'Text',
'lines':'Lines',
'changed':'Changed',
'created':'Created',
'objectBrowser.renameMember.invalid.input': `New member name must be different from it's current name`,
'objectBrowser.createFilter': `Create new filter`,
'objectBrowser.deleteObject.progress':'Deleting object {0}...',
'objectBrowser.renameObject.progress': `Renaming object {0} {1} to {2}...`,
'objectBrowser.moveObject.progress': `Moving object {0} {1} to {2}...`
```

### Checklist
* [x] have tested my change
* [ ] updated relevant documentation

### CODE REVIEW

**Comment by worksofliam** [comment]
I just did a quick code review tonight and I'll get to functional testing tomorrow. This is a big PR, which is fine, but it likely has a lot more going on in the PR than it needs. For example:

* you've added new callback logic to make handling config changes easier (which is lovely btw)
* cleanup to the `package.json` and hiding a lot of commands from the palette

Nonetheless, as much as I'd like these kind of things to be separate PRs.. I am super happy with how good of a cleanup this is.

Thank you, @sebjulliand. This is some excellent work

**Comment by sebjulliand** [comment]
@worksofliam yeah, sorry, I went a bit overboard with this one 😅

**Comment by chrjorgensen** [comment]
@sebjulliand I translated the new texts to Danish with some minor fixes and regrouping.

**Review by chrjorgensen — APPROVED** [review]
@sebjulliand Looking good! 😍 

Feel free to merge at any time... 👍

**Comment by sebjulliand** [comment]
> @sebjulliand Looking good! 😍
> 
> Feel free to merge at any time... 👍

Awesome! Thank you so much @chrjorgensen for validating this!

**Pull request merged**
