### PR TITLE
Fixed format RPGLE column assist

### PR DESCRIPTION
**Pull request by worksofliam**
### Changes

Adds a new language feature for fixed-format RPGLE. Now, when editing fixed format, the areas of input on the line for the current lines specification will be highlighted. The user can also hover their mouse over an area for a short description on the line.

As well as that, a new command has been added that allows the users to open prompt to make it easier to put text into the correct position.

### Checklist

* [ ] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in the README
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by benetti-smeup** [comment]
@worksofliam 
Hi Liam.
If you could make a vsix I would like to help testing this PR.
Thanks

**Comment by worksofliam** [comment]
@benetti-smeup yup, I can get that done for you tomorrow or tonight.

I need to bring in lots of commits to this branch.

**Comment by benetti-smeup** [comment]
Thanks.
there is no rush.

Il Gio 16 Set 2021, 23:26 barry ***@***.***> ha scritto:

**Comment by worksofliam** [comment]
The VSIX is inside the zip file: [code-for-ibmi-0.7.6.vsix.zip](https://github.com/halcyon-tech/vscode-ibmi/files/7187317/code-for-ibmi-0.7.6.vsix.zip)

This is how you try it out:

1. Install the .vsix
2. Enable this new feature in the VS Code settings (not the connection settings!)

image

3. Open up fixed format code (not containing **FREE). You will see the hover suggestions working.
4. To launch the assistant, press F1 and run the 'Launch Column Assistant':

image

**Comment by benetti-smeup** [comment]
@worksofliam I used the column assist for a few days and I think is a very good work and it can be released.

I found a little issue: indicators before factor1 are not recognized.
Column assistant

I also think that it will be useful to have a shortcut to move the cursor to the next field.

**Comment by worksofliam** [comment]
@benetti-smeup let me work on those and then maybe we could release it!

**Comment by worksofliam** [comment]
[code-for-ibmi-0.7.7.vsix.zip](https://github.com/halcyon-tech/vscode-ibmi/files/7206050/code-for-ibmi-0.7.7.vsix.zip)

@benetti-smeup Any chance you can test this build on the C spec issue you found earlier? I added the parts for them,

**Comment by benetti-smeup** [comment]
@worksofliam I tested 0.7.7 and it works! Thanks

**Comment by worksofliam** [comment]
@benetti-smeup Do you think the command to launch the RPG assist deserves a default keyboard shortcut?

**Comment by worksofliam** [comment]
I'm giving it shift+f4.

**Pull request merged**
